CREATE OR REPLACE PROCEDURE actualizar_datawarehouse()
LANGUAGE plpgsql
AS $$
BEGIN
    -- ==========================================
    -- 1. CARGA INCREMENTAL DE DIMENSIONES (UPSERT)
    -- ==========================================
    
    INSERT INTO "SEGURO_DW_G27797047".DIM_CLIENTE (COD_CLIENTE, NB_CLIENTE, CI_RIF, TELEFONO, DIRECCION, SEXO, EMAIL)
    SELECT cod_cliente, nb_cliente, ci_rif, telefono, direccion, sexo, email FROM "SEGURO_G27797047".CLIENTE
    ON CONFLICT (COD_CLIENTE) DO UPDATE SET NB_CLIENTE = EXCLUDED.NB_CLIENTE, TELEFONO = EXCLUDED.TELEFONO, DIRECCION = EXCLUDED.DIRECCION, EMAIL = EXCLUDED.EMAIL;

    INSERT INTO "SEGURO_DW_G27797047".DIM_PRODUCTO (COD_PRODUCTO, NB_PRODUCTO, DESCRIP_PRODUCTO, COD_TIPO_PRODUCTO, NB_TIPO_PRODUCTO, CALIFICACION)
    SELECT p.cod_producto, p.nb_producto, p.descripcion, tp.cod_tipo_producto, tp.nb_tipo_producto, p.calificacion
    FROM "SEGURO_G27797047".PRODUCTO p JOIN "SEGURO_G27797047".TIPO_PRODUCTO tp ON p.cod_tipo_producto = tp.cod_tipo_producto
    ON CONFLICT (COD_PRODUCTO) DO UPDATE SET NB_PRODUCTO = EXCLUDED.NB_PRODUCTO, CALIFICACION = EXCLUDED.CALIFICACION;

    INSERT INTO "SEGURO_DW_G27797047".DIM_CONTRATO (NRO_CONTRATO, DESCRIP_CONTRATO)
    SELECT nro_contrato, descrip_contrato FROM "SEGURO_G27797047".CONTRATO
    ON CONFLICT (NRO_CONTRATO) DO UPDATE SET DESCRIP_CONTRATO = EXCLUDED.DESCRIP_CONTRATO;

    INSERT INTO "SEGURO_DW_G27797047".DIM_SUCURSAL (COD_SUCURSAL, NB_SUCURSAL, COD_CIUDAD, NB_CIUDAD, COD_PAIS, NB_PAIS)
    SELECT s.cod_sucursal, s.nb_sucursal, c.cod_ciudad, c.nb_ciudad, p.cod_pais, p.nb_pais
    FROM "SEGURO_G27797047".SUCURSAL s JOIN "SEGURO_G27797047".CIUDAD c ON s.cod_ciudad = c.cod_ciudad JOIN "SEGURO_G27797047".PAIS p ON c.cod_pais = p.cod_pais
    ON CONFLICT (COD_SUCURSAL) DO UPDATE SET NB_SUCURSAL = EXCLUDED.NB_SUCURSAL;

    INSERT INTO "SEGURO_DW_G27797047".DIM_SINIESTRO (NRO_SINIESTRO, DESCRIP_SINIESTRO)
    SELECT nro_siniestro, descripcion_siniestro FROM "SEGURO_G27797047".SINIESTRO
    ON CONFLICT (NRO_SINIESTRO) DO UPDATE SET DESCRIP_SINIESTRO = EXCLUDED.DESCRIP_SINIESTRO;

    INSERT INTO "SEGURO_DW_G27797047".DIM_EVALUACION_SERVICIO (COD_EVALUACION, NB_DESCRIP)
    SELECT cod_evaluacion_servicio, nb_descripcion FROM "SEGURO_G27797047".EVALUACION_SERVICIO
    ON CONFLICT (COD_EVALUACION) DO UPDATE SET NB_DESCRIP = EXCLUDED.NB_DESCRIP;

    -- >>> DIMENSIÓN NUEVA AGREGADA <<<
    INSERT INTO "SEGURO_DW_G27797047".DIM_ESTADO_CONTRATO (COD_ESTADO, DESCRIP_ESTADO) VALUES
        ('AC', 'Activo'),
        ('VE', 'Vencido'),
        ('SU', 'Suspendido')
    ON CONFLICT (COD_ESTADO) DO UPDATE SET DESCRIP_ESTADO = EXCLUDED.DESCRIP_ESTADO;

    -- ==========================================
    -- 2. CARGA DE TABLAS DE HECHOS (RELOAD)
    -- ==========================================
    
    -- FACT_REGISTRO_CONTRATO (ACTUALIZADO CON LAS 11 COLUMNAS NUEVAS)
    TRUNCATE TABLE "SEGURO_DW_G27797047".FACT_REGISTRO_CONTRATO;
    INSERT INTO "SEGURO_DW_G27797047".FACT_REGISTRO_CONTRATO (
        SK_DIM_TIEMPO_FECHA_INICIO, SK_DIM_TIEMPO_FECHA_FIN, SK_DIM_CLIENTE,
        SK_DIM_CONTRATO, SK_DIM_PRODUCTO, SK_DIM_ESTADO_CONTRATO,
        SK_DIM_SUCURSAL, MONTO, CANTIDAD, CANTIDAD_CLIENTE, CANTIDAD_PRODUCTO, CANTIDAD_CONTRATO
    )
    SELECT
        to_char(rc.fecha_inicio, 'YYYYMMDD')::integer,
        to_char(rc.fecha_fin, 'YYYYMMDD')::integer,
        dc.SK_DIM_CLIENTE, dcon.SK_DIM_CONTRATO, dp.SK_DIM_PRODUCTO, de.SK_DIM_ESTADO,
        dsuc.SK_DIM_SUCURSAL, rc.monto, 1, 1, 1, 1
    FROM "SEGURO_G27797047".REGISTRO_CONTRATO rc
    JOIN "SEGURO_DW_G27797047".DIM_CLIENTE dc ON rc.cod_cliente = dc.COD_CLIENTE
    JOIN "SEGURO_DW_G27797047".DIM_CONTRATO dcon ON rc.nro_contrato = dcon.NRO_CONTRATO
    JOIN "SEGURO_DW_G27797047".DIM_PRODUCTO dp ON rc.cod_producto = dp.COD_PRODUCTO
    LEFT JOIN "SEGURO_DW_G27797047".DIM_ESTADO_CONTRATO de
        ON de.COD_ESTADO = CASE rc.estado_contrato WHEN 'activo' THEN 'AC' WHEN 'vencido' THEN 'VE' WHEN 'suspendido' THEN 'SU' END
    JOIN "SEGURO_G27797047".CLIENTE c ON rc.cod_cliente = c.cod_cliente
    JOIN "SEGURO_DW_G27797047".DIM_SUCURSAL dsuc ON c.cod_sucursal = dsuc.COD_SUCURSAL;

    -- FACT_REGISTRO_SINIESTRO
    TRUNCATE TABLE "SEGURO_DW_G27797047".FACT_REGISTRO_SINIESTRO;
    INSERT INTO "SEGURO_DW_G27797047".FACT_REGISTRO_SINIESTRO (
        SK_FECHA_SINIESTRO, SK_FECHA_RESPUESTA, SK_DIM_CLIENTE, SK_DIM_CONTRATO, 
        SK_DIM_SUCURSAL, SK_DIM_PRODUCTO, SK_DIM_SINIESTRO, CANTIDAD, 
        MONTO_RECONOCIDO, MONTO_SOLICITADO, ID_RECHAZO
    )
    SELECT 
        to_char(rs.fecha_siniestro, 'YYYYMMDD')::integer, 
        to_char(rs.fecha_respuesta, 'YYYYMMDD')::integer,
        dc.SK_DIM_CLIENTE, dcon.SK_DIM_CONTRATO, ds.SK_DIM_SUCURSAL, 
        dp.SK_DIM_PRODUCTO, dsin.SK_DIM_SINIESTRO, 1, 
        rs.monto_reconocido, rs.monto_solicitado, rs.id_rechazo
    FROM "SEGURO_G27797047".REGISTRO_SINIESTRO rs
    JOIN "SEGURO_G27797047".REGISTRO_CONTRATO rc ON rs.nro_contrato = rc.nro_contrato
    JOIN "SEGURO_G27797047".CLIENTE c ON rc.cod_cliente = c.cod_cliente
    JOIN "SEGURO_DW_G27797047".DIM_CLIENTE dc ON rc.cod_cliente = dc.COD_CLIENTE
    JOIN "SEGURO_DW_G27797047".DIM_CONTRATO dcon ON rs.nro_contrato = dcon.NRO_CONTRATO
    JOIN "SEGURO_DW_G27797047".DIM_SUCURSAL ds ON c.cod_sucursal = ds.COD_SUCURSAL
    JOIN "SEGURO_DW_G27797047".DIM_PRODUCTO dp ON rc.cod_producto = dp.COD_PRODUCTO
    JOIN "SEGURO_DW_G27797047".DIM_SINIESTRO dsin ON rs.nro_siniestro = dsin.NRO_SINIESTRO;

    -- FACT_EVALUACION_SERVICIO (CARGA INCREMENTAL - UPSERT)
    INSERT INTO "SEGURO_DW_G27797047".FACT_EVALUACION_SERVICIO (
        SK_DIM_CLIENTE, SK_DIM_PRODUCTO, SK_DIM_EVALUACION_SERVICIO,
        SK_DIM_TIEMPO_FECHA_EVALUACION, CANTIDAD, RECOMIENDA_AMIGO
    )
    SELECT dc.SK_DIM_CLIENTE, dp.SK_DIM_PRODUCTO, de.SK_DIM_EVALUACION,
        to_char(r.fecha_evaluacion, 'YYYYMMDD')::integer, 1,
        CASE WHEN r.recomienda_amigo = 'SI' THEN 1.0 ELSE 0.0 END
    FROM "SEGURO_G27797047".RECOMIENDA r
    JOIN "SEGURO_DW_G27797047".DIM_CLIENTE dc ON r.cod_cliente = dc.COD_CLIENTE
    JOIN "SEGURO_DW_G27797047".DIM_PRODUCTO dp ON r.cod_producto = dp.COD_PRODUCTO
    JOIN "SEGURO_DW_G27797047".DIM_EVALUACION_SERVICIO de ON r.cod_evaluacion_servicio = de.COD_EVALUACION
    ON CONFLICT (SK_DIM_CLIENTE, SK_DIM_PRODUCTO, SK_DIM_EVALUACION_SERVICIO, SK_DIM_TIEMPO_FECHA_EVALUACION)
    DO UPDATE SET RECOMIENDA_AMIGO = EXCLUDED.RECOMIENDA_AMIGO;

    -- FACT_METAS
    TRUNCATE TABLE "SEGURO_DW_G27797047".FACT_METAS;
    INSERT INTO "SEGURO_DW_G27797047".FACT_METAS (
        SK_DIM_FECHA_INICIO_META, SK_DIM_FECHA_FIN_META,
        SK_DIM_PRODUCTO,
        MONTO_META_INGRESO, META_RENOVACION, META_ASEGURADOS
    )
    SELECT
        to_char(m.fecha_inicio, 'YYYYMMDD')::integer,
        to_char(m.fecha_fin, 'YYYYMMDD')::integer,
        dp.SK_DIM_PRODUCTO,
        m.meta_ingreso, m.meta_renovacion, m.meta_asegurados
    FROM "SEGURO_G27797047".METAS m
    JOIN "SEGURO_DW_G27797047".DIM_PRODUCTO dp ON m.cod_producto = dp.COD_PRODUCTO;

END;
$$;