-- =========================================================================
-- FASE C: MODELO DIMENSIONAL (DATA WAREHOUSE)
-- =========================================================================

-- Creación y selección del esquema del Data Warehouse
CREATE SCHEMA IF NOT EXISTS "SEGURO_DW_G27797047";
SET search_path TO "SEGURO_DW_G27797047";

-- ==========================================
-- DIMENSIONES CONFORMADAS
-- ==========================================

-- DIM_TIEMPO
CREATE TABLE DIM_TIEMPO (
    SK_DIM_TIEMPO INTEGER PRIMARY KEY,
    COD_ANNIO INTEGER,
    COD_MES INTEGER,
    COD_DIA INTEGER,
    DESC_MES VARCHAR(50),
    DESC_TRIMESTRE VARCHAR(15),
    DESC_SEMESTRE VARCHAR(10),
    FECHA_COMPLETA DATE
);

-- DIM_CLIENTE
CREATE TABLE DIM_CLIENTE (
    SK_DIM_CLIENTE SERIAL PRIMARY KEY,
    COD_CLIENTE VARCHAR(10) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    NB_CLIENTE VARCHAR(150),
    CI_RIF VARCHAR(20),
    TELEFONO VARCHAR(20),
    DIRECCION TEXT,
    SEXO CHAR(1),
    EMAIL VARCHAR(100)
);

-- DIM_PRODUCTO
CREATE TABLE DIM_PRODUCTO (
    SK_DIM_PRODUCTO SERIAL PRIMARY KEY,
    COD_PRODUCTO VARCHAR(10) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    NB_PRODUCTO VARCHAR(100),
    DESCRIP_PRODUCTO TEXT,
    COD_TIPO_PRODUCTO VARCHAR(10),
    NB_TIPO_PRODUCTO VARCHAR(100),
    CALIFICACION INTEGER
);

-- DIM_CONTRATO
CREATE TABLE DIM_CONTRATO (
    SK_DIM_CONTRATO SERIAL PRIMARY KEY,
    NRO_CONTRATO VARCHAR(20) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    DESCRIP_CONTRATO TEXT
);

-- DIM_SUCURSAL
CREATE TABLE DIM_SUCURSAL (
    SK_DIM_SUCURSAL SERIAL PRIMARY KEY,
    COD_SUCURSAL VARCHAR(10) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    NB_SUCURSAL VARCHAR(100),
    COD_CIUDAD VARCHAR(10),
    NB_CIUDAD VARCHAR(100),
    COD_PAIS VARCHAR(10),
    NB_PAIS VARCHAR(100)
);

-- DIM_ESTADO_CONTRATO
CREATE TABLE DIM_ESTADO_CONTRATO (
    SK_DIM_ESTADO SERIAL PRIMARY KEY,
    COD_ESTADO CHAR(2) UNIQUE, -- Clave Natural con restricción UNIQUE para Carga Incremental
    DESCRIP_ESTADO VARCHAR(50)
);

-- DIM_EVALUACION_SERVICIO
CREATE TABLE DIM_EVALUACION_SERVICIO (
    SK_DIM_EVALUACION SERIAL PRIMARY KEY,
    COD_EVALUACION VARCHAR(10) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    NB_DESCRIP VARCHAR(50)
);

-- DIM_SINIESTRO
CREATE TABLE DIM_SINIESTRO (
    SK_DIM_SINIESTRO SERIAL PRIMARY KEY,
    NRO_SINIESTRO VARCHAR(20) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    DESCRIP_SINIESTRO TEXT
);

-- ==========================================
-- TABLAS DE HECHOS (FACTS)
-- ==========================================

-- FACT_REGISTRO_CONTRATO
CREATE TABLE FACT_REGISTRO_CONTRATO (
    SK_DIM_TIEMPO_FECHA_INICIO INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_TIEMPO_FECHA_FIN INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_CONTRATO INTEGER REFERENCES DIM_CONTRATO(SK_DIM_CONTRATO),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_ESTADO_CONTRATO INTEGER REFERENCES DIM_ESTADO_CONTRATO(SK_DIM_ESTADO),
    SK_DIM_SUCURSAL INTEGER REFERENCES DIM_SUCURSAL(SK_DIM_SUCURSAL),
    MONTO REAL,
    CANTIDAD INTEGER,
    CANTIDAD_CLIENTE INTEGER,
    CANTIDAD_PRODUCTO INTEGER,
    CANTIDAD_CONTRATO INTEGER,
    PRIMARY KEY (SK_DIM_TIEMPO_FECHA_INICIO, SK_DIM_CLIENTE, SK_DIM_CONTRATO, SK_DIM_PRODUCTO)
);

-- FACT_REGISTRO_SINIESTRO
CREATE TABLE FACT_REGISTRO_SINIESTRO (
    SK_FECHA_SINIESTRO INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_FECHA_RESPUESTA INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_CONTRATO INTEGER REFERENCES DIM_CONTRATO(SK_DIM_CONTRATO),
    SK_DIM_SUCURSAL INTEGER REFERENCES DIM_SUCURSAL(SK_DIM_SUCURSAL),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_SINIESTRO INTEGER REFERENCES DIM_SINIESTRO(SK_DIM_SINIESTRO),
    CANTIDAD INTEGER,
    MONTO_RECONOCIDO REAL,
    MONTO_SOLICITADO REAL,
    ID_RECHAZO CHAR(2),
    PRIMARY KEY (SK_FECHA_SINIESTRO, SK_DIM_CLIENTE, SK_DIM_CONTRATO, SK_DIM_SINIESTRO)
);

-- FACT_EVALUACION_SERVICIO
CREATE TABLE FACT_EVALUACION_SERVICIO (
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_EVALUACION_SERVICIO INTEGER REFERENCES DIM_EVALUACION_SERVICIO(SK_DIM_EVALUACION),
    SK_DIM_TIEMPO_FECHA_EVALUACION INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    CANTIDAD INTEGER,
    RECOMIENDA_AMIGO REAL,
    PRIMARY KEY (SK_DIM_CLIENTE, SK_DIM_PRODUCTO, SK_DIM_EVALUACION_SERVICIO, SK_DIM_TIEMPO_FECHA_EVALUACION)
);

-- FACT_METAS
CREATE TABLE FACT_METAS (
    SK_DIM_FECHA_INICIO_META INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_FECHA_FIN_META INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    MONTO_META_INGRESO REAL,
    META_RENOVACION INTEGER,
    META_ASEGURADOS INTEGER,
    PRIMARY KEY (SK_DIM_FECHA_INICIO_META, SK_DIM_PRODUCTO)
);
-- =========================================================================
-- FASE D: POBLADO DE LA DIMENSIÓN TIEMPO
-- =========================================================================
INSERT INTO "SEGURO_DW_G27797047".DIM_TIEMPO (
    SK_DIM_TIEMPO, COD_ANNIO, COD_MES, COD_DIA, DESC_MES, DESC_TRIMESTRE, DESC_SEMESTRE, FECHA_COMPLETA
)
SELECT 
    to_char(fecha, 'YYYYMMDD')::integer, extract(year from fecha)::integer, extract(month from fecha)::integer, extract(day from fecha)::integer,
    CASE extract(month from fecha)
        WHEN 1 THEN 'Enero' WHEN 2 THEN 'Febrero' WHEN 3 THEN 'Marzo' WHEN 4 THEN 'Abril' WHEN 5 THEN 'Mayo' WHEN 6 THEN 'Junio'
        WHEN 7 THEN 'Julio' WHEN 8 THEN 'Agosto' WHEN 9 THEN 'Septiembre' WHEN 10 THEN 'Octubre' WHEN 11 THEN 'Noviembre' WHEN 12 THEN 'Diciembre'
    END,
    'Trim. ' || extract(quarter from fecha), CASE WHEN extract(month from fecha) <= 6 THEN 'Semestre 1' ELSE 'Semestre 2' END, fecha
FROM generate_series('2015-01-01'::date, '2030-12-31'::date, '1 day'::interval) as fecha;
