-- Creación y selección del esquema del Data Warehouse
CREATE SCHEMA IF NOT EXISTS "SEGURO_DW_G27797047";
SET search_path TO "SEGURO_DW_G27797047";

-- ==========================================
-- DIMENSIONES CONFORMADAS
-- ==========================================

-- DIM_TIEMPO[cite: 1]
CREATE TABLE DIM_TIEMPO (
    SK_DIM_TIEMPO INTEGER PRIMARY KEY,
    COD_ANNIO INTEGER,
    COD_MES INTEGER,
    COD_DIA INTEGER,
    DESC_MES VARCHAR(50),
    DESC_TRIMESTRE VARCHAR(10),
    DESC_SEMESTRE VARCHAR(10),
    FECHA_COMPLETA DATE
);

-- DIM_CLIENTE[cite: 1]
CREATE TABLE DIM_CLIENTE (
    SK_DIM_CLIENTE SERIAL PRIMARY KEY,
    COD_CLIENTE VARCHAR(10) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    NB_CLIENTE VARCHAR(150),
    CI_RIF VARCHAR(20),
    TELEFONO VARCHAR(20),
    DIRECCION TEXT,
    SEXO CHAR(1),
    EMAIL VARCHAR(100)
);

-- DIM_PRODUCTO[cite: 1]
CREATE TABLE DIM_PRODUCTO (
    SK_DIM_PRODUCTO SERIAL PRIMARY KEY,
    COD_PRODUCTO VARCHAR(10) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    NB_PRODUCTO VARCHAR(100),
    DESCRIP_PRODUCTO TEXT,
    COD_TIPO_PRODUCTO VARCHAR(10),
    NB_TIPO_PRODUCTO VARCHAR(100),
    CALIFICACION INTEGER
);

-- DIM_CONTRATO[cite: 1]
CREATE TABLE DIM_CONTRATO (
    SK_DIM_CONTRATO SERIAL PRIMARY KEY,
    NRO_CONTRATO VARCHAR(20) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    DESCRIP_CONTRATO TEXT
);

-- DIM_SUCURSAL[cite: 1]
CREATE TABLE DIM_SUCURSAL (
    SK_DIM_SUCURSAL SERIAL PRIMARY KEY,
    COD_SUCURSAL VARCHAR(10) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    NB_SUCURSAL VARCHAR(100),
    COD_CIUDAD VARCHAR(10),
    NB_CIUDAD VARCHAR(100),
    COD_PAIS VARCHAR(10),
    NB_PAIS VARCHAR(100)
);

-- DIM_ESTADO_CONTRATO[cite: 1]
CREATE TABLE DIM_ESTADO_CONTRATO (
    SK_DIM_ESTADO SERIAL PRIMARY KEY,
    COD_ESTADO CHAR(2) UNIQUE, -- Clave Natural con restricción UNIQUE para Carga Incremental
    DESCRIP_ESTADO VARCHAR(50)
);

-- DIM_EVALUACION_SERVICIO[cite: 1]
CREATE TABLE DIM_EVALUACION_SERVICIO (
    SK_DIM_EVALUACION SERIAL PRIMARY KEY,
    COD_EVALUACION VARCHAR(10) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    NB_DESCRIP VARCHAR(50)
);

-- DIM_SINIESTRO[cite: 1]
CREATE TABLE DIM_SINIESTRO (
    SK_DIM_SINIESTRO SERIAL PRIMARY KEY,
    NRO_SINIESTRO VARCHAR(20) UNIQUE NOT NULL, -- Clave Natural con restricción UNIQUE para Carga Incremental
    DESCRIP_SINIESTRO TEXT
);

-- ==========================================
-- TABLAS DE HECHOS (FACTS)
-- ==========================================

-- FACT_REGISTRO_CONTRATO[cite: 1]
CREATE TABLE FACT_REGISTRO_CONTRATO (
    SK_DIM_TIEMPO_FECHA_INICIO INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_TIEMPO_FECHA_FIN INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_CONTRATO INTEGER REFERENCES DIM_CONTRATO(SK_DIM_CONTRATO),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_ESTADO_CONTRATO INTEGER REFERENCES DIM_ESTADO_CONTRATO(SK_DIM_ESTADO),
    MONTO REAL,
    CANTIDAD INTEGER,
    CANTIDAD_CLIENTE INTEGER,
    CANTIDAD_PRODUCTO INTEGER,
    CANTIDAD_CONTRATO INTEGER
);

-- FACT_REGISTRO_SINIESTRO[cite: 1]
CREATE TABLE FACT_REGISTRO_SINIESTRO (
    SK_FECHA_SINIESTRO INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_FECHA_RESPUESTA INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_CONTRATO INTEGER REFERENCES DIM_CONTRATO(SK_DIM_CONTRATO),
    SK_DIM_SUCURSAL INTEGER REFERENCES DIM_SUCURSAL(SK_DIM_SUCURSAL),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_SINIESTRO INTEGER REFERENCES DIM_SINIESTRO(SK_DIM_SINIESTRO),
    CANTIDAD INTEGER,
    MONTO_RECONOCIDO REAL,
    MONTO_SOLICITADO REAL,
    ID_RECHAZO CHAR(2)
);

-- FACT_EVALUACION_SERVICIO[cite: 1]
CREATE TABLE FACT_EVALUACION_SERVICIO (
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_EVALUACION_SERVICIO INTEGER REFERENCES DIM_EVALUACION_SERVICIO(SK_DIM_EVALUACION),
    CANTIDAD INTEGER,
    RECOMIENDA_AMIGO REAL
);

-- FACT_METAS[cite: 1]
CREATE TABLE FACT_METAS (
    SK_DIM_FECHA_INICIO_META INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_FECHA_FIN_META INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_CONTRATO INTEGER REFERENCES DIM_CONTRATO(SK_DIM_CONTRATO),
    MONTO_META_INGRESO REAL,
    META_RENOVACION INTEGER,
    META_ASEGURADOS INTEGER
);